### ISSUE TITLE
Unsupported opcode: WITH_EXCEPT_START

### ISSUE THREAD

**Issue by Marshallsus** [zrax/pycdc#207]
Unsupported opcode: WITH_EXCEPT_START
from re import split
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import Select
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import time
import os
import sys
import string
import random
from random import choice
import requests
from requests.api import get
import json
import names
import datetime
import colorama
from colorama import Fore, Style, init
import threading
from queue import Queue
import itertools
from anticaptcha.funcaptchaproxyless import *
from anticaptcha.funcaptchaproxyon import *
from AuthGG import *
from fake_useragent import UserAgent
import zipfile
colorama.init(True, **('autoreset',))
path = os.path.join(os.getcwd(), 'settings.txt')
with open(path) as f:
    sdata = json.load(f)
    None(None, None, None)
# WARNING: Decompyle incomplete

**Comment by PMK89** [comment]
I got the same issue:

`Unsupported opcode: WITH_EXCEPT_START
print('Loading...')
from web3 import Web3
import datetime
import threading
import json
...
numTokensSold = 0
walletBalance = 0
foundTokenThreadBusy = False
configFilePath = os.path.abspath('') + '\\config.json'
with open(configFilePath, 'r') as configdata:
    data = configdata.read()
    None(None, None, None)
# WARNING: Decompyle incomplete`

**Comment by furritos** [comment]
Some things to to note, this `opcode` was fixed in #195.  I think for the sake of posterity, I'm attaching the PYC file that @PMK89 is referring to and it's accompanying debug file  ==> 
[BSCTokenSniper_debug.txt](https://github.com/zrax/pycdc/files/7499870/BSCTokenSniper_debug.txt)

**Comment by furritos** [comment]
Duplicate of #195

**Comment by Marshallsus** [comment]
> Some things to note, this `opcode` was fixed in #195. I think for the sake of posterity, I'm attaching the debugged PYC file that @PMK89 is referring to ==> [BSCTokenSniper_debug.txt](https://github.com/zrax/pycdc/files/7499870/BSCTokenSniper_debug.txt)

i see that they fixed 2/4 of the opcodes are you sure they fixed all of them?

**Comment by furritos** [comment]
Maybe "fixed" was the wrong term but it's "loosely" addressed in the the master branch.... though I don't know if it's enough as I'm not as well versed in decompiling as I'd like.

**Comment by ChrisEnglish90** [comment]
Any eta on fixing this?

**Comment by ChrisEnglish90** [comment]
> Unsupported opcode: WITH_EXCEPT_START from re import split from selenium import webdriver from selenium.webdriver.common.by import By from selenium.webdriver.chrome.options import Options from selenium.webdriver.support.ui import Select from selenium.webdriver.common.action_chains import ActionChains from selenium.webdriver.chrome.service import Service from selenium.webdriver.support.ui import WebDriverWait from selenium.webdriver.support import expected_conditions as EC import time import os import sys import string import random from random import choice import requests from requests.api import get import json import names import datetime import colorama from colorama import Fore, Style, init import threading from queue import Queue import itertools from anticaptcha.funcaptchaproxyless import * from anticaptcha.funcaptchaproxyon import * from AuthGG import * from fake_useragent import UserAgent import zipfile colorama.init(True, **('autoreset',)) path = os.path.join(os.getcwd(), 'settings.txt') with open(path) as f: sdata = json.load(f) None(None, None, None)
> 
> # WARNING: Decompyle incomplete

Did you get it fixed?

**Comment by bohong65** [comment]
Same error, It seems that opcode "WITH_EXCEPT_START" has not been fixed yet

**Comment by iboosting** [comment]
The error still occurs in the latest master branch version: 
Unsupported opcode: WITH_EXCEPT_START

**Comment by zrax** [comment]
Duplicate #450
